import { Flag } from "../shared.jsx";
import { ScreenTitle } from "../layout/Menu.jsx";
import { FixturesToggle } from "../schedule/ScheduleScreens.jsx";

export function GroupTable({ title, rows }) {
  return <div className="mx-auto w-[94%] overflow-hidden rounded-[1.6rem] bg-[#EFE7D8] text-[#072D1D] ring-1 ring-[#0B5F35]/8 shadow-[0_8px_24px_rgba(7,45,29,0.04)]"><div className="bg-[#0B5F35] px-3 py-2.5 text-center text-[17px] font-black tracking-[-0.025em] text-[#F5F0E6]">{title}</div><div className="p-3"><div className="mb-1.5 grid grid-cols-[24px_minmax(0,1.9fr)_repeat(6,24px)] items-center gap-[3px] px-2 text-center text-[8px] font-black uppercase tracking-[0.08em] text-[#072D1D]/42"><span>#</span><span className="pl-1 text-left">Team</span><span>P</span><span>W</span><span>D</span><span>L</span><span>GD</span><span>Pts</span></div>{rows.map((row, index) => <div key={row.team} className="mb-1.5 grid grid-cols-[24px_minmax(0,1.9fr)_repeat(6,24px)] items-center gap-[3px] rounded-xl bg-[#F8F4EC] px-2 py-2 text-center text-[9px] font-semibold text-[#072D1D]/80 ring-1 ring-[#0B5F35]/5 last:mb-0"><span>{index + 1}</span><span className="flex min-w-0 items-center gap-1.5 pl-1 text-left"><Flag team={row.team} /><span className="truncate uppercase tracking-[0.015em]">{row.team}</span></span><span>{row.played}</span><span>{row.won}</span><span>{row.drawn}</span><span>{row.lost}</span><span>{row.gd}</span><span className="font-black">{row.pts}</span></div>)}</div></div>;
}

function KnockoutBracket({ round32 = [] }) {
  const FlagSlot = ({ team = null, compact = false, large = false }) => <div className={`flex items-center justify-center overflow-hidden rounded-[0.6rem] border border-[#0B5F35]/10 bg-[#7DAA8F] text-[#F5F0E6] ${large ? "h-9 w-14 text-[9px]" : compact ? "h-6 w-8 text-[7px]" : "h-7 w-10 text-[8px]"}`}>{team && team !== "TBC" ? <Flag team={team} className="h-full w-full rounded-none" /> : <span className="font-black uppercase tracking-[0.06em]">TBC</span>}</div>;
  const MatchSlot = ({ match, compact = false, large = false }) => <div className="flex items-center justify-center gap-[2px]"><FlagSlot team={match?.home} compact={compact} large={large} /><FlagSlot team={match?.away} compact={compact} large={large} /></div>;
  const Row = ({ count, matches = [], compact = false, gap = "gap-1", large = false }) => <div className={`grid ${count === 8 ? "grid-cols-8" : count === 4 ? "grid-cols-4" : count === 2 ? "grid-cols-2" : "grid-cols-1"} ${gap}`}>{Array.from({ length: count }).map((_, index) => <MatchSlot key={index} match={matches[index]} compact={compact} large={large} />)}</div>;
  const StageLabel = ({ children }) => <div className="text-center text-[7px] font-black uppercase tracking-[0.12em] text-[#7DAA8F]">{children}</div>;
  return <div className="mx-auto w-[94%] overflow-hidden rounded-[1.6rem] bg-[#EFE7D8] text-[#072D1D] ring-1 ring-[#0B5F35]/8 shadow-[0_8px_24px_rgba(7,45,29,0.04)]"><div className="bg-[#0B5F35] px-3 py-2.5 text-center text-[17px] font-black tracking-[-0.025em] text-[#F5F0E6]">TOURNAMENT BRACKET</div><div className="p-2"><div className="rounded-[1.5rem] bg-[#F8F4EC] px-2 py-3 ring-1 ring-[#0B5F35]/8"><div className="flex flex-col items-center"><StageLabel>ROUND OF 32</StageLabel><div className="mt-2"><Row count={8} matches={round32.slice(0, 8)} compact gap="gap-[2px]" /></div><div className="mt-5"><StageLabel>ROUND OF 16</StageLabel><div className="mt-2"><Row count={4} gap="gap-2" /></div></div><div className="mt-6"><StageLabel>QUARTER-FINALS</StageLabel><div className="mt-2"><Row count={2} gap="gap-2" /></div></div><div className="mt-6"><StageLabel>SEMI-FINALS</StageLabel><div className="mt-2"><Row count={1} gap="gap-2" /></div></div><div className="mt-6"><StageLabel>FINAL</StageLabel><div className="mt-2"><Row count={1} large /></div></div><div className="mt-6"><StageLabel>SEMI-FINALS</StageLabel><div className="mt-2"><Row count={1} gap="gap-2" /></div></div><div className="mt-6"><StageLabel>QUARTER-FINALS</StageLabel><div className="mt-2"><Row count={2} gap="gap-2" /></div></div><div className="mt-5"><StageLabel>ROUND OF 16</StageLabel><div className="mt-2"><Row count={4} gap="gap-2" /></div></div><div className="mt-5"><StageLabel>ROUND OF 32</StageLabel><div className="mt-2"><Row count={8} matches={round32.slice(8, 16)} compact gap="gap-[2px]" /></div></div></div></div></div></div>;
}

export function GroupsScreen({ allGroups, qualifiers, menuProps, standingsView, onStandingsViewChange, knockoutFixtures }) {
  return <main className="flex min-h-0 flex-1 flex-col gap-2"><ScreenTitle {...menuProps}>STANDINGS</ScreenTitle><FixturesToggle value={standingsView} onChange={onStandingsViewChange} /><section className="min-h-0 flex-1 overflow-auto py-1"><div className="space-y-2">{standingsView === "group" && allGroups.map(({ group, rows }) => <GroupTable key={group} title={`GROUP ${group}`} rows={rows} />)}{standingsView === "group" && <GroupTable title="BEST 3RD-PLACE TEAMS" rows={qualifiers.best3RDs} />}{standingsView === "knockout" && <KnockoutBracket round32={knockoutFixtures} />}</div></section></main>;
}
