import { ASSETS } from "../../data/assets.js";
import { getTeamTheme, teamCode } from "../../data/teams.js";
import { Flag, HamburgerIcon } from "../shared.jsx";
import { Shell } from "../layout/Layout.jsx";
import { MenuDropdown } from "../layout/Menu.jsx";

function PenaltyDots({ results = [] }) { return <div className="flex items-center justify-center gap-1">{[0, 1, 2, 3, 4].map((index) => { const value = results[index]; const colour = value === "goal" ? "bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.85)]" : value === "miss" ? "bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.85)]" : "bg-[#F7D117] shadow-[0_0_8px_rgba(247,209,23,0.55)]"; return <span key={index} className={`h-1 w-1 rounded-full ring-[0.5px] ring-[#F5F0E6]/10 ${colour}`} />; })}</div>; }

function ScoreboardHeader({ menuProps }) { return <div className="relative bg-[#0B5F35] px-4 py-4"><div className="absolute inset-x-0 bottom-0 h-px bg-[#F5F0E6]/10" /><img src={ASSETS.mondayLogo} alt="Monday Cup" className="absolute left-[-1px] bottom-0 h-[66px] w-[66px] object-contain" /><div className="flex items-center justify-center"><div className="text-[38px] font-black leading-[0.94] tracking-[-0.025em] text-[#F5F0E6]">LIVE MATCH</div></div><button onClick={menuProps.onToggleMenu} className="absolute right-3 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-lg bg-[#0B5F35] pb-[1px] text-lg font-black leading-none text-[#F5F0E6]"><HamburgerIcon /></button>{menuProps.menuOpen && <MenuDropdown onClose={menuProps.onToggleMenu} onMatch={menuProps.onMatch} onFixtures={menuProps.onFixtures} onGroups={menuProps.onGroups} onRestart={menuProps.onRestart} />}</div>; }

function DotMatrixScoreboard({ team, opponent, score = [0, 0], playerPens, opponentPens, commentary, menuProps, stageLabel = "GROUP STAGE" }) { const theme = getTeamTheme(team || "Mexico"); return <div className="relative overflow-visible"><div className="overflow-visible rounded-[1.6rem] bg-[#072D1D] text-[#F5F0E6]" style={{ backgroundImage: "radial-gradient(rgba(245,240,230,0.16) 1px, transparent 1px)", backgroundSize: "7px 7px" }}><ScoreboardHeader menuProps={menuProps} /><div className="px-4 pt-3 pb-4 text-center"><div className="mb-3 text-[10px] font-black uppercase tracking-[0.14em] text-[#F7D117] drop-shadow-[0_0_8px_rgba(247,209,23,0.55)]">{stageLabel}</div><div className="grid grid-cols-[32px_52px_1fr_96px_1fr_52px_32px] grid-rows-[32px_12px] items-center gap-x-2 gap-y-1"><div className="col-start-1 row-start-1 flex justify-center"><Flag team={team || "Team A"} className="h-6 w-8" /></div><div className="col-start-2 row-start-1 text-center text-[20px] font-black uppercase tracking-[0.02em] text-[#F7D117]">{teamCode(team || "Team A")}</div><div className="col-start-4 row-start-1 flex items-center justify-center text-center text-[28px] font-black tabular-nums text-[#F7D117]">{score[0]} - {score[1]}</div><div className="col-start-6 row-start-1 text-center text-[20px] font-black uppercase tracking-[0.02em] text-[#F7D117]">{teamCode(opponent || "Team B")}</div><div className="col-start-7 row-start-1 flex justify-center"><Flag team={opponent || "Team B"} className="h-6 w-8" /></div><div className="col-start-2 row-start-2 flex justify-center"><PenaltyDots results={playerPens} /></div><div className="col-start-6 row-start-2 flex justify-center"><PenaltyDots results={opponentPens} /></div></div></div><div className="border-t border-[#F5F0E6]/10 px-4 py-3 text-center" style={{ backgroundColor: theme.bg }}><div className="text-[13px] font-black uppercase tracking-[0.14em]" style={{ color: theme.text }}>{commentary}</div></div></div></div>; }

function FullTimeModal({ result, onNext }) { const title = result.status === "qualified" ? "YOU QUALIFIED!" : result.status === "eliminated" ? "ELIMINATED!" : result.status === "champion" ? "CHAMPIONS!" : result.won ? "YOU WON" : "YOU LOST"; const buttonLabel = result.status === "eliminated" ? "PLAY AGAIN" : result.status === "champion" ? "VIEW BRACKET" : "NEXT MATCH"; return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-[#072D1D]/45 px-5"><div className="w-full max-w-sm rounded-[2rem] bg-[#F5F0E6] p-5 text-center text-[#0B5F35] shadow-[0_20px_60px_rgba(7,45,29,0.22)]"><div className="text-[10px] font-black uppercase tracking-[0.22em] text-[#0B5F35]/45">FULL TIME</div><div className="mt-2 text-[34px] font-black uppercase tracking-[-0.03em]">{title}</div><div className="mt-3 rounded-[1.2rem] bg-[#EFE7D8] px-4 py-3 text-[18px] font-black uppercase tracking-[0.04em]"><span>{teamCode(result.home)}</span><span className="mx-3 tabular-nums">{result.homeGoals}-{result.awayGoals}</span><span>{teamCode(result.away)}</span></div><button onClick={onNext} className="mt-5 h-12 w-full rounded-full bg-[#0B5F35] text-[13px] font-black uppercase tracking-[0.12em] text-[#F5F0E6]">{buttonLabel}</button></div></div>; }

export function MatchScreen({ team, opponent, score, matchResult, onQuickWin, onNextMatch, menuProps, stageLabel = "GROUP STAGE" }) { const pitchBackground = { backgroundColor: "#7BCB59", backgroundImage: "repeating-linear-gradient(90deg,#6FC14F 0px,#6FC14F 64px,#7BCB59 64px,#7BCB59 128px),radial-gradient(rgba(255,255,255,0.035) 1px, transparent 1px)", backgroundSize: "128px 100%, 6px 6px" }; const commentary = `${(team || "TEAM A").toUpperCase()} TO SHOOT`; const playerPens = score[0] > 0 ? ["goal"] : []; const opponentPens = score[1] > 0 ? ["goal"] : []; return <Shell><div className="h-[100dvh] overflow-hidden px-5 pt-3" style={pitchBackground}><DotMatrixScoreboard team={team} opponent={opponent} score={score} playerPens={playerPens} opponentPens={opponentPens} commentary={commentary} menuProps={menuProps} stageLabel={stageLabel} /><div className="mt-2 rounded-[2.2rem] bg-[#0B5F35] p-5 text-center text-[#F5F0E6] shadow-[0_18px_60px_rgba(7,45,29,0.18)]"><div className="text-4xl">⚽</div><p className="mt-2 text-sm uppercase tracking-[0.12em]">NOT READY YET</p><button onClick={onQuickWin} className="mt-5 inline-flex h-11 items-center justify-center rounded-full bg-[#F5F0E6] px-6 text-[13px] font-black uppercase tracking-[0.12em] text-[#0B5F35]">WIN 1-0</button></div>{matchResult && <FullTimeModal result={matchResult} onNext={onNextMatch} />}</div></Shell>; }
