import { BrandMark, MondayLogo } from "../shared.jsx";

export function Shell({ children }) { return <div className="flex min-h-[100dvh] justify-center bg-[#F5F0E6] text-[#072D1D] antialiased"><div className="min-h-[100dvh] w-full max-w-md">{children}</div></div>; }
export function PageFrame({ children }) { return <div className="flex h-[100dvh] flex-col overflow-hidden bg-[#F5F0E6] px-5 pb-0 pt-3">{children}</div>; }
export function Footer() { return <footer className="mt-auto h-[58px] shrink-0 bg-[#F5F0E6] pt-2 text-center"><div className="flex h-full items-start justify-center border-t border-[#0B5F35]/12 pt-2"><BrandMark /></div></footer>; }
export function GreenCard({ children }) { return <section className="rounded-[2.2rem] border border-white/10 bg-[#0B5F35] p-5 text-[#F5F0E6]">{children}</section>; }
export function Hero() { return <div className="flex h-[116px] flex-col items-center justify-center text-center"><div className="text-[10px] font-semibold uppercase tracking-[0.26em] text-[#0B5F35]/45">THE JOURNEY BEGINS</div><div className="mt-2 text-[44px] font-black uppercase leading-[0.9] tracking-[-0.015em] text-[#0B5F35]">CHOOSE A TEAM</div></div>; }
export function BottomTagline() { return <div className="flex flex-1 items-center justify-center pb-2 pt-3 text-center"><p className="inline-block whitespace-nowrap text-[10px] font-bold uppercase tracking-[0.14em] text-[#072D1D]/45">PICK A TEAM · TAKE YOUR CHANCES · LIFT THE CUP</p></div>; }
export function SelectionLayout({ children }) { return <Shell><PageFrame><header className="text-center"><div className="flex justify-center"><MondayLogo /></div><Hero /></header><main className="flex min-h-0 flex-1 flex-col py-2"><div className="mt-8">{children}</div><BottomTagline /></main><Footer /></PageFrame></Shell>; }
export function DrawerShell({ children }) { return <div className="fixed inset-0 z-50 bg-[#F5F0E6]"><div className="mx-auto flex h-[100dvh] max-w-md flex-col px-5 pb-0 pt-3">{children}<Footer /></div></div>; }
